/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f0xx.h"

void uart2_init(void) {

    RCC->AHBENR  |= RCC_AHBENR_GPIOAEN;
    RCC->APB1ENR |= RCC_APB1ENR_USART2EN;


    GPIOA->MODER &= ~(3 << (2 * 2));
    GPIOA->MODER |=  (2 << (2 * 2));

    GPIOA->AFR[0] &= ~(0xF << (4 * 2));
    GPIOA->AFR[0] |=  (1 << (4 * 2));


    USART2->BRR = 480000 / 96;
    USART2->CR1 = USART_CR1_TE | USART_CR1_UE;
}

void uart2_write_char(char c) {
    while (!(USART2->ISR & USART_ISR_TXE));
    USART2->TDR = c;
}

void uart2_write_string(const char *str) {
    while (*str) {
        uart2_write_char(*str++);
    }
}

int main(void) {
    uart2_init();

    while (1) {
        uart2_write_string("Hello from UART2\r\n");
        for (volatile int i = 0; i < 500000; i++);
    }
}

