/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f0xx.h"

void delay_ms(volatile uint32_t ms) {
    for (volatile uint32_t i = 0; i < ms * 800; ++i);
}

void gpio_init(void) {

    RCC->AHBENR |= RCC_AHBENR_GPIOCEN;


    GPIOC->MODER &= ~(3 << (2 * 9));
    GPIOC->MODER |=  (1 << (2 * 9));


    GPIOC->OTYPER &= ~(1 << 9);


    GPIOC->OSPEEDR |= (1 << (2 * 9));


    GPIOC->PUPDR &= ~(3 << (2 * 9));
}

int main(void) {
    gpio_init();

    while (1) {
        GPIOC->ODR |= (1 << 9);
        delay_ms(500);

        GPIOC->ODR &= ~(1 << 9);
        delay_ms(500);
    }
}
